### ISSUE TITLE
Function filterFileSize translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#100]
We need translation of Documentation for filterFileSize and **src/filters/i18n/Filters18n.js**:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-file-size

**Comment by zdilarr** [comment]
done

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterFileSize again.
I improved and changed the structure.

docs/src/views/Functions/PageFileSize/i18n (Arguments)

**Comment by babeyeva** [comment]
Ok
