### ISSUE TITLE
Function filterDate translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#102]
We need translations of Documentation for filterDate:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-date

**Comment by shafedh** [comment]
ready to test

**Comment by ilia-brykin** [comment]
@shafedh  We need translations of Documentation for filterDate again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterDate/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
