### ISSUE TITLE
Function filterDate translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#103]
We need translation of Documentation for filterDate
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-date

**Comment by zdilarr** [comment]
done

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterDate again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterDate/i18n (Arguments)

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok
