### ISSUE TITLE
Function filterFloat

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#104]
We need extensions for function filterFloat.
Arguments:

- suffix
- digits
- digitGrouping
und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-float
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok
