### ISSUE TITLE
Function filterFloat translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#105]
We need translations of Documentation for filterFloat:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-float

**Comment by shafedh** [comment]
ready to test

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterFloat again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterFloat/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
