### ISSUE TITLE
Function filterFloat translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#106]
We need translation of Documentation for filterFloat
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-float

**Comment by zdilarr** [comment]
done

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterFloat again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterFloat/i18n (Arguments)

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok
