### ISSUE TITLE
Function filterCurrency

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#107]
We need extensions for function filterCurrency.
Arguments:

- suffix
- digits
- digitGrouping
und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-currency
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by ilia-brykin** [comment]
I did some more refactoring. You need to check DE and RU again.
Data types are now translated.

**Comment by babeyeva** [comment]
URL: https://ilia-brykin.github.io/aloha/#/filter-currency
Language: RU
Need correct translation in description for filterCurrency and for Arguments in string [digitGrouping=true] (Логическое значение).
I recommend in description: "... . Она принимает числовое значение и возвращает строку, представляющую значение с указанной валютой, количеством десятичных знаков, суффиксом и, при необходимости, группировкой цифр (разделение разрядов числа тысячами). ..."
I recommend in Arguments in string [digitGrouping=true] (Логическое значение): "Указывает, активировано ли группировка цифр для вставки разделителя разряда числа тысячами в отформатированную строку"
![filterCurrency incorrent description](https://github.com/ilia-brykin/aloha/assets/146904622/b6d9edb8-e879-42dd-b1c3-aa901135ab27)

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
Ok
