### ISSUE TITLE
Function filterCurrency translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#108]
We need translations of Documentation for filterCurrency:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-currency

**Comment by shafedh** [comment]
ready to test

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterCurrency again.
I improved and changed the structure.

- docs/src/views/Functions/PageFilterCurrency/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
