### ISSUE TITLE
Function filterCurrency translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#109]
We need translation of Documentation for filterCurrency
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-currency

**Comment by zdilarr** [comment]
done

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterCurrency again.
I improved and changed the structure.

- docs/src/views/Functions/PageFilterCurrency/i18n (Arguments)

**Comment by zdilarr** [comment]
done
