### ISSUE TITLE
Hamburger Menu: ctrl + click on an item closes menu

### ISSUE THREAD

**Issue by zdilarr** [ilia-brykin/aloha#112]
AMenu: In **mobile** view of the page, choose a clickable menu item off a hamburger menu.  
For Example,

Main Menu -> Filters -> filterBoolean 
ctrl+click to open link in new tab

expected behavior: menu stays open. Link is opened in new tab.
actual behavior: link is opened in new tab but menu closes completely

Note: Behavior is correct for wider screens, it can only be reproduced for mobile view.

**Comment by ilia-brykin** [comment]
at work

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
Ok
