### ISSUE TITLE
Aloha Documentation: Language is being reset anytime a page is reloaded.

### ISSUE THREAD

**Issue by zdilarr** [ilia-brykin/aloha#113]
In the upper right corner of the documentation page user can switch to preferred langauge. 
Refreshing the page resets language back to Deutsch.

Same for links opened in new page, they are in Deutsch regardless of what was chosen as a preferred language.

We need a solution where the documentation stays in a preferred language.

Technical discussion
- cookies
- Broswer Preferred language

**Comment by ilia-brykin** [comment]
done

**Comment by babeyeva** [comment]
ОК
