### ISSUE TITLE
isArrayOf__:  document behavior for empty arrays

### ISSUE THREAD

**Issue by zdilarr** [ilia-brykin/aloha#125]
When documenting utils function isArrayOfStrings and isArrayOfArrays I noticed the lack of examples for input [].
The return value for empty array input is  true, which to me is somewhat counterintuitive.

Reason for it is behavior of lodash function every, which comes from EcmaScript spec 
https://es5.github.io/#x15.4.4.16

My proposition is to add it to JSApi. 
@ilia-brykin  please review this proposition.

**Comment by ilia-brykin** [comment]
[] must return false. I fixed it

**Comment by ilia-brykin** [comment]
@zdilarr If you agree with the decision, you can close the issue

**Comment by zdilarr** [comment]
Took a look at aa68f432a4be88e09bcdb9396f984e8125e0556a  - looks good. Closing the issue.
