### ISSUE TITLE
AWizard accessibility test 9.1.1 Textalternativen

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#140]
AWizard accessibility test 9.1.1 Textalternativen

- 9.1.1.1a Alternativtexte für Bedienelemente
- 9.1.1.1b Alternativtexte für Grafiken und Objekte
- 9.1.1.1c Leere alt-Attribute für Layoutgrafiken
- 9.1.1.1d Alternativen für CAPTCHAs

**Comment by babeyeva** [comment]
All these **Prüfkriterien** are not applicable for AWizard.
