### ISSUE TITLE
AWizard accessibility test 9.1.4 Unterscheidbar

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#142]
AWizard accessibility test 9.1.4 Unterscheidbar
https://bitvtest.de/pruefverfahren/bitv-20-web

**Comment by babeyeva** [comment]
**Prüfschritt 9.1.4.1** corresponds.

**Prüfschritt 9.1.4.2** is not applicable for AWizard.

**Prüfschritt 9.1.4.3** corresponds.

**Prüfschritt 9.1.4.4** corresponds.

**Prüfschritt 9.1.4.5** is not applicable for AWizard.

**Prüfschritt 9.1.4.10** corresponds.

**Prüfschritt 9.1.4.11** corresponds.

**Prüfschritt 9.1.4.12** 

I can't open necessary Bookmaklet to check. I need help

**Prüfschritt 9.1.4.13** corresponds.
