### ISSUE TITLE
AWizard accessibility test 9.2.1 Tastaturbedienbar

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#143]
AWizard accessibility test 9.2.1 Tastaturbedienbar
https://bitvtest.de/pruefverfahren/bitv-20-web

**Comment by babeyeva** [comment]
**Prüfschritt 9.2.1.1** corresponds

**Prüfschritt 9.2.1.2** corresponds

**Prüfschritt 9.2.1.4** corresponds
