### ISSUE TITLE
AWizard accessibility test 9.2.2 Ausreichend Zeit

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#144]
AWizard accessibility test 9.2.2 Ausreichend Zeit
https://bitvtest.de/pruefverfahren/bitv-20-web

**Comment by babeyeva** [comment]
Prüfschritt 9.2.2.1 is not applicable for AWizard.

Prüfschritt 9.2.2.2 is not applicable for AWizard.
