### ISSUE TITLE
AWizard accessibility test 9.2.3 Anfälle

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#145]
AWizard accessibility test 9.2.3 Anfälle
https://bitvtest.de/pruefverfahren/bitv-20-web

**Comment by babeyeva** [comment]
**Prüfschritt 9.2.3.1** 

I need help

**Comment by babeyeva** [comment]
Prüfschritt 9.2.3.1 is not applicable for AWizard.
