### ISSUE TITLE
AWizard accessibility test 9.3.3 Eingabeunterstützung

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#150]
AWizard accessibility test 9.3.3 Eingabeunterstützung
https://bitvtest.de/pruefverfahren/bitv-20-web

**Comment by babeyeva** [comment]
Prüfschritt 9.3.3.1 is not applicable for AWizard.
Prüfschritt 9.3.3.2 corresponds
Prüfschritt 9.3.3.3 is not applicable for AWizard.
Prüfschritt 9.3.3.4 is not applicable for AWizard.
