### ISSUE TITLE
AGroup passes entire error instead of boolean indicator to ALabel

### ISSUE THREAD

**Issue by zdilarr** [ilia-brykin/aloha#166]
In case of errors when submitting the form for an input inside AGroup, the entire error for the input with corresponding ID is passed to ALabel. Prop isError is defined as a boolean.  That leads to warning in console. Invalid prop: type check failed for prop "isError". Expected Boolean, got Array.

I believe error is not critical since object gets evaluated to truthy value and works correctly. Still, we should correct this behavior

https://github.com/ilia-brykin/aloha/blob/master/src/ui/AGroup/AGroup.js#L168

**Comment by ilia-brykin** [comment]
done
