### ISSUE TITLE
Multi-Colum-Sorting: Click and keyboard combination does not work

### ISSUE THREAD

**Issue by zdilarr** [ilia-brykin/aloha#31]
**Steps to reproduce:**
ATable with :is-sorting-multi-column="true" and sorting-multi-column-key="shift". Reproducible on DOCS page aloha/#/table-sort

**Expected Result:**
Click + shift sorts table by multiple selected columns.

**Current behavior:**
Table sorted by a single column, combo has no effect. (If relevant, reproduced with Chrome on Linux)

**Comment by ilia-brykin** [comment]
at work

**Comment by ilia-brykin** [comment]
fixed
