### ISSUE TITLE
AAlert translation (HR)

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#45]
We need translation for the component AAlert. (HR)
URL: https://ilia-brykin.github.io/aloha/#/alert
Language: HR

- `_A_ALERT_GROUP_BTN_CLOSE_HEADER_`
- `_A_ALERT_GROUP_BTN_CLOSE_DESCRIPTION_`
- `_A_ALERT_PROPS_BTN_CLOSE_ATTRIBUTES_DESCRIPTION_`

![AAlert_hr](https://github.com/ilia-brykin/aloha/assets/39484012/e70eec86-222f-4182-b7bf-0a27ade40153)

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Well done.
