### ISSUE TITLE
AShowMore Missing translation (DE)

### ISSUE THREAD

**Issue by babeyeva** [ilia-brykin/aloha#48]
URL: https://ilia-brykin.github.io/aloha/#/show-more
language: DE
![2023-10-04_20-28-24](https://github.com/ilia-brykin/aloha/assets/146904622/64798f93-0455-40b5-81ba-0b4738b43caa)

**Comment by ilia-brykin** [comment]
fixed

**Comment by babeyeva** [comment]
Well done.
