### ISSUE TITLE
AShowMore Missing Translation (HR)

### ISSUE THREAD

**Issue by babeyeva** [ilia-brykin/aloha#50]
URL: https://ilia-brykin.github.io/aloha/#/show-more
Language: Hrvatski
![2023-10-04_22-10-10](https://github.com/ilia-brykin/aloha/assets/146904622/7a13e71e-3f29-4834-b6a1-00beda94c506)

**Comment by zdilarr** [comment]
in progress

**Comment by zdilarr** [comment]
done, assigned to @babeyeva for test

**Comment by babeyeva** [comment]
ok
