### ISSUE TITLE
Incorrect layout in AWizard.

### ISSUE THREAD

**Issue by NKDante** [ilia-brykin/aloha#52]
Incorrect positioning in AWizard with two-digit numbers.
![image](https://github.com/ilia-brykin/aloha/assets/29443235/390a0562-777a-433b-8fc2-2df8dbb11114)

**Comment by ilia-brykin** [comment]
Done. 
This can be checked on the page https://ilia-brykin.github.io/aloha/#/wizard
You need to scroll down to the example: `_A_WIZARD_GROUP_DEMO_HEADER_`.
On this page, for now, there is no need to pay attention to the lack of translations.
Here you can play with the wizard and try to break it or catch any errors.

**Comment by babeyeva** [comment]
Bugs are not found
