### ISSUE TITLE
AList Extensions

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#65]
We need extensions for AList.
Props: 
1. classItem
2. classMain
3. data
4. isDataSimpleArray
5. isHtml
6. keyChildren
7. keyId
8. keyLabel
9. keyLabelCallback
10. labelTag
11. listItemTag
12. separator
13. tag
And expanding the documentation
URL: https://ilia-brykin.github.io/aloha/#/list

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Need translation for the button JA-NEIN in Props: is-html
Language: RU
URL: https://ilia-brykin.github.io/aloha/#/list
![AList Отображение списка в текстовом или HTML-формате Кнопка ДА-НЕТ не переведены](https://github.com/ilia-brykin/aloha/assets/146904622/312696c5-9677-4fec-88c0-8680939a62e5)

Russian grammar is OK

**Comment by babeyeva** [comment]
Now it's ok
