### ISSUE TITLE
AList translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#66]
We need translations of Documentation for AList:

- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/list

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Need translation for the button JA-NEIN in Props: is-html
Language: EN, AR, ES, FR, IT
URL: https://ilia-brykin.github.io/aloha/#/list
![AList in Props is-html BUG in button JA-NEIN](https://github.com/ilia-brykin/aloha/assets/146904622/11b1fe5d-4c8f-4f4e-8613-bea96785d74b)

**Comment by babeyeva** [comment]
Now it's ok
