### ISSUE TITLE
AList translations HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#67]
We need translations of Documentation for AList:

- HR

URL: https://ilia-brykin.github.io/aloha/#/list

**Comment by zdilarr** [comment]
in progress

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Need translation for the button JA-NEIN in Props: is-html
Language: HR
URL: https://ilia-brykin.github.io/aloha/#/list
![AList in Props is-html BUG in button JA-NEIN](https://github.com/ilia-brykin/aloha/assets/146904622/b4f2255e-4f01-4f1e-a9be-2fa5c9c3e413)

**Comment by zdilarr** [comment]
thanks for reporting.
@babeyeva small remark, screenshot corresponds to italian, HR is for Hrvatski. maybe copy paste issue.
anyways, it ss fixed now for all languages, changes are in master.

**Comment by babeyeva** [comment]
@zdilarr Thanks for your remark. This problem was in all languages & in three similar issues. So  I decided to make one screenshot for all issues. 
Now it's ok.
