### ISSUE TITLE
Function filterList translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#70]
We need translation of Documentation for filterList:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-list

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterList again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterList/i18n (Arguments)

**Comment by zdilarr** [comment]
done
