### ISSUE TITLE
Function filterLimitTo

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#71]
We need extensions for function filterLimitTo.
Arguments:
- limit,
- maxThreeDots
und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-limit-to
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested
