### ISSUE TITLE
Function filterLimitTo translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#72]
We need translations of Documentation for filterLimitTo:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-limit-to

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterLimitTo again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterLimitTo/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test
