### ISSUE TITLE
Function filterLimitTo translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#73]
We need translation of Documentation for filterLimitTo:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-limit-to

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@zdilarr We need translations of Documentation for filterLimitTo again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterLimitTo/i18n (Arguments)

**Comment by zdilarr** [comment]
done
