### ISSUE TITLE
Function filterBoolean

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#74]
We need extensions for function filterBoolean.
Arguments:
- trueValue
- falseValue
- useNil
und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-boolean
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Russian grammar is Ok.
Need translation in code of Basic usage; useNil  (words JA,NEIN) 
Language: RU
URL: https://ilia-brykin.github.io/aloha/#/filter-boolean
![FilterBoolean in Basic usage   useNil no translation in code (Ja-Nein)](https://github.com/ilia-brykin/aloha/assets/146904622/170da903-a9da-4ef3-b1fe-163dec4b7338)

**Comment by ilia-brykin** [comment]
fixed.

**Comment by ilia-brykin** [comment]
I did some more refactoring. You need to check DE and RU again.
Data types are now translated.

**Comment by babeyeva** [comment]
Ok
