### ISSUE TITLE
Function filterBoolean translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#75]
We need translations of Documentation for filterBoolean:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-boolean

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Need translation in code of Basic usage; useNil (words JA,NEIN)
Language: EN, AR, ES, FR, IT
URL: https://ilia-brykin.github.io/aloha/#/filter-boolean
![FilterBoolean in Basic usage   useNil no translation in code (Ja-Nein)](https://github.com/ilia-brykin/aloha/assets/146904622/ace1a876-362c-4b7e-b378-48a285afe9f6)

**Comment by ilia-brykin** [comment]
Bug fixed.

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterBoolean again. 
I improved and changed the structure.

- docs/src/i18n (types)
- docs/src/views/Functions/i18n (Composition API)
- docs/src/views/Functions/PageFilterBoolean/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Need translation for Documentation of filterBoolean
Language: EN, AR, ES, FR, IT
URL: https://ilia-brykin.github.io/aloha/#/filter-boolean
![FilterBoolean need translation EN](https://github.com/ilia-brykin/aloha/assets/146904622/e80f7d35-5453-4b8f-9ba9-b3be455863c7)

**Comment by shafedh** [comment]
Ready to test

**Comment by babeyeva** [comment]
Ок
