### ISSUE TITLE
Function filterBoolean translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#76]
We need translation of Documentation for filterBoolean:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-boolean

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Need translation in code of Basic usage; useNil (words JA,NEIN)
Language: HR
URL: https://ilia-brykin.github.io/aloha/#/filter-boolean
![FilterBoolean in Basic usage   useNil no translation in code (Ja-Nein)](https://github.com/ilia-brykin/aloha/assets/146904622/8664d4fc-d431-48c9-b620-f942b3cf189d)

**Comment by ilia-brykin** [comment]
Bug fixed.

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterBoolean again. 
I improved and changed the structure.

- docs/src/i18n (types)
- docs/src/views/Functions/i18n (Composition API)
- docs/src/views/Functions/PageFilterBoolean/i18n (Arguments)

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok
