### ISSUE TITLE
Function filterDefaultForEmpty

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#77]
We need extensions for function filterDefaultForEmpty.
Arguments:
- emptyValue
und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-default-for-empty
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok
