### ISSUE TITLE
Function filterDefaultForEmpty translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#78]
We need translations of Documentation for filterDefaultForEmpty:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-default-for-empty

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterDefaultForEmpty again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterDefaultForEmpty/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
