### ISSUE TITLE
Function filterDefaultForEmpty translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#79]
We need translation of Documentation for filterDefaultForEmpty:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-default-for-empty

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@zdilarr We need translations of Documentation for filterDefaultForEmpty again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterDefaultForEmpty/i18n (Arguments)

**Comment by zdilarr** [comment]
done
