### ISSUE TITLE
Function filterEmail translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#82]
We need translation of Documentation for filterEmail:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-email

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@zdilarr We need translations of Documentation for filterEmail again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterEmail/i18n (Arguments)

**Comment by zdilarr** [comment]
done
