### ISSUE TITLE
Function filterPropertyByValue

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#83]
We need extensions for function filterPropertyByValue.
Arguments:
- mapping
- defaultValue

und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-property-by-value
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested
