### ISSUE TITLE
Function filterPropertyByValue translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#84]
We need translations of Documentation for filterPropertyByValue:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-property-by-value

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterPropertyByValue again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterPropertyByValue/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
