### ISSUE TITLE
Function filterPropertyByValue translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#85]
We need translation of Documentation for filterPropertyByValue:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-property-by-value

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterPropertyByValue again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterPropertyByValue/i18n (Arguments)

**Comment by zdilarr** [comment]
done
