### ISSUE TITLE
Function filterSearchHighlight

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#86]
We need extensions for function filterSearchHighlight.
Arguments:
- searchModel
- searchClass
und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-search-highlight
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested
