### ISSUE TITLE
Function filterSearchHighlight translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#87]
We need translations of Documentation for filterSearchHighlight:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-search-highlight

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterSearchHighlight again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterSearchHighlight/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
