### ISSUE TITLE
Function filterSearchHighlight translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#88]
We need translation of Documentation for filterSearchHighlight:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-search-highlight

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterSearchHighlight again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterSearchHighlight/i18n (Arguments)

**Comment by zdilarr** [comment]
done
