### ISSUE TITLE
Function filterLink

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#89]
We need extensions for function filterLink.
Arguments:

- linkText
- protocol
- target
- linkClass
und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-link
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
There's incorrect translation in description for function filterLink.
I recommend "Функция проверяет достоверность URL-адреса и обеспечивает его надежную вставку в ссылку HTML"
Language: RU
URL: https://ilia-brykin.github.io/aloha/#/filter-link
![FilterLink description - incorrect translation RU](https://github.com/ilia-brykin/aloha/assets/146904622/d4d10038-d9fb-445a-bdf0-676a985a8b4b)

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok
