### ISSUE TITLE
Function filterLink translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#90]
We need translations of Documentation for filterLink:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-link

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterLink again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterLink/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
