### ISSUE TITLE
Function filterLink translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#91]
We need translation of Documentation for filterLink:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-link

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterLink again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterLink/i18n (Arguments)

**Comment by zdilarr** [comment]
done
