### ISSUE TITLE
Function filterJson

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#92]
We need extensions for function filterJson.
Arguments:

- replacer
- space

und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-json
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok
