### ISSUE TITLE
Function filterJson translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#93]
We need translations of Documentation for filterJson:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-json

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterJson again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterJson/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
