### ISSUE TITLE
Function filterJson translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#94]
We need translation of Documentation for filterJson:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-json

**Comment by zdilarr** [comment]
done

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterJson again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterJson/i18n (Arguments)
