### ISSUE TITLE
Function filterKeyValue

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#95]
We need extensions for function filterKeyValue.
Arguments:

- value

und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-key-value
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok
