### ISSUE TITLE
Function filterKeyValue translations EN, AR, ES, FR, IT

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#96]
We need translations of Documentation for filterKeyValue:
- EN
- AR
- ES
- FR
- IT
URL: https://ilia-brykin.github.io/aloha/#/filter-key-value

**Comment by shafedh** [comment]
ready to test

**Comment by ilia-brykin** [comment]
@shafedh We need translations of Documentation for filterKeyValue again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterKeyValue/i18n (Arguments)

**Comment by shafedh** [comment]
ready to test

**Comment by babeyeva** [comment]
Ok
