### ISSUE TITLE
Function filterKeyValue translation HR

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#97]
We need translation of Documentation for filterKeyValue:
- HR
URL: https://ilia-brykin.github.io/aloha/#/filter-key-value

**Comment by zdilarr** [comment]
done

**Comment by ilia-brykin** [comment]
@zdilarr  We need translations of Documentation for filterKeyValue again.
I improved and changed the structure.

docs/src/views/Functions/PageFilterKeyValue/i18n (Arguments)

**Comment by zdilarr** [comment]
done

**Comment by babeyeva** [comment]
Ok
