### ISSUE TITLE
Function filterFileSize

### ISSUE THREAD

**Issue by ilia-brykin** [ilia-brykin/aloha#98]
We need extensions for function filterFileSize.
Arguments:

- units
- sourceUnits
- digits

und documentation.
URL: https://ilia-brykin.github.io/aloha/#/filter-file-size
Translations: DE, RU

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by ilia-brykin** [comment]
Ready. Documentation for languages DE and RU can be tested.
Russian grammar should be tested

**Comment by babeyeva** [comment]
Ok
